name: Create UffizziCluster on PullRequest

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: uffizzi-client-clone-1    # Add your cluster name here.
  GKE_ZONE: us-central1   # Add your cluster zone here.

jobs:
  test-kubectl:
    name: Test Kubectl
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@1bee7de035d65ec5da40a31f8589e240eba8fde5
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud container clusters get-credentials uffizzi-client-clone-1 --zone us-central1 --project uffizzi-pro-qa-gke

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        kubectl get namespaces
