name: Create UffizziCluster on PullRequest

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    branches: [ main ]

env:
  # These are all temporary for this proof-of-concept.
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: uffizzi-client-clone-1    # Add your cluster name here.
  GKE_ZONE: us-central1   # Add your cluster zone here.
  #USE_GKE_GCLOUD_AUTH_PLUGIN: true
  # Once finished, this workflow will include Uffizzi credentials instead of GCP.

  # In practice, clusters will probably get a unique ID and the workflow will identify them using metadata.
  UCLUSTER_NAME: cluster-${{ github.run_id }}
  PR_NUMBER: ${{ github.event.number }}

jobs:
  create-uffizzi-cluster:
    name: Create Uffizzi Cluster
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY }}'
        project_id: ${{ env.PROJECT_ID }}

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}
        install_components: 'gke-gcloud-auth-plugin'

    - run: |-
        gcloud container clusters get-credentials ${GKE_CLUSTER} --zone ${GKE_ZONE} --project ${PROJECT_ID}

    - name: create
      if: ${{ endsWith(github.event.action, 'opened') }} # "opened" or "reopened"
      run: |-
        envsubst < uffizzi-cluster.template.yaml > uffizzi-cluster.rendered.yaml
        cat uffizzi-cluster.rendered.yaml #debug
        kubectl apply -f uffizzi-cluster.rendered.yaml
        # TODO: fetch and decode kubeconfig
        # TODO: deploy sample app

    - name: update
      if: ${{ github.event.action == 'synchronize' }}
      run: |-
        echo TODO
        kubectl get namespace
        # TODO: fetch and decode kubeconfig
        # TODO: re-deploy sample app

    - name: destroy
      if: ${{ github.event.action == 'closed' }}
      run: |-
        kubectl delete namespace ${UCLUSTER_NAME}

    # Deploy the Docker image to the GKE cluster
#    - name: UffizziCluster + Helm
#      run: |-
#        ## Set Namespace
#        export PR_NUMBER=${{github.event.number}}
#        export NAMESPACE=pr-simple-k8s-app-$PR_NUMBER
#        export HELM_MANIFEST=$(helm template $PR_NUMBER ./chart -n $NAMESPACE)
#        yq e '.spec.manifests = strenv(HELM_MANIFEST) |
#          .metadata.namespace = strenv(NAMESPACE)' uffizzi-cluster.yml > uffizzi-cluster-configured.yml
#        kubectl create namespace $NAMESPACE
#        kubectl apply -f uffizzi-cluster-configured.yml
